fixing loop

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -17,14 +17,17 @@ done
 
 if [ -f ${HOME}/.icescrum_cli ]
 then
+  set -a
 	. ${HOME}/.icescrum_cli
-else
-	if [ -z ${ICESCRUM_URL} ] || [ -z ${ICESCRUM_USER} ]	\
-		|| [ -z ${ICESCRUM_PASSWD} ]						\
-		|| [ -z ${ICESCRUM_PROJECT_ID} ]					\
-		|| [ -z ${ICESCRUM_PROJECT_NAME} ]
-	then
-		echo "File '.icescrum_cli' not found on home (${HOME})"
-		exit 1
-	fi
+  set +a
 fi
+
+if [ -z ${ICESCRUM_URL} ] || [ -z ${ICESCRUM_USER} ]	\
+  || [ -z ${ICESCRUM_PASSWD} ]						\
+  || [ -z ${ICESCRUM_PROJECT_ID} ]					\
+  || [ -z ${ICESCRUM_PROJECT_NAME} ]
+then
+  echo "File '.icescrum_cli' not found on home (${HOME})"
+  exit 1
+fi
+
